changelog:
  exclude:
    labels:
      - ignore
      - documentation
      - internal
      - maintenance
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - feature
        - new
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
        - bugfix
    - title: "📚 Documentation"
      labels:
        - documentation
        - docs
    - title: "🧪 Testing"
      labels:
        - test
        - testing
    - title: "🔧 Maintenance"
      labels:
        - maintenance
        - chore
        - refactor
        - internal
    - title: "⚡ Performance"
      labels:
        - performance
        - optimization
    - title: "🔒 Security"
      labels:
        - security
        - vulnerability
    - title: "💥 Breaking Changes"
      labels:
        - breaking
        - breaking-change
        - major
  template: |
    ## 🎉 Release ${{version}}
    
    ${{changelog}}
    
    ---
    
    **Full Changelog**: ${{compare_url}}
    
    **Installation**: `npm install tranzilajs@${{version}}`
    
    *This release was automatically generated by GitHub Actions* 