// Tranzila-specific constants
export const ApiBaseUrls = {
  PAYMENTS: 'https://api.tranzila.com',
  REPORTS: 'https://report.tranzila.com',
  SECURE5: 'https://secure5.tranzila.com',
  CHECKOUT: 'https://direct.tranzila.com'
} as const;

export const IframePaths = {
  "IFRAME_NEW(NEW)": "iframenew.php",
  "NEW_IFRAME(OLD)": "newiframe.php"
} as const

export const ApiEndpoints = {
  "BIT_INIT": "/v1/transaction/bit/init",
  "BIT_REFUND": "/v1/transaction/bit/refund",
  "CARD_REFUND": "/cgi-bin/tranzila71u.cgi",
  "STO_CREATE": "/v2/sto/create",
  "STO_UPDATE": "/v1/sto/update",
  "STO_RETRIEVE": "/v1/stos/get",
  "SEARCH_TRANSACTIONS": "/v1/transaction",
} as const

export const CredTypes = {
  "CREDIT_CARD": 1,
  "CREDIT": 6,
  "PAYMENTS": 8
} as const;

export const CardIssuers = {
  "ISRACART": 1,
  "VISA_CAL": 2,
  "DINERS": 3,
  "AMERICAN_EXPRESS": 4,
  "JCB": 5,
  "LEUMI_CARD": 6
} as const;

export const CardAcquirers = {
  /** Unkown */
  "UNKNOWN": 0,
  "ISRACART": 1,
  "VISA_CAL": 2,
  "DINERS": 3,
  "AMERICAN_EXPRESS": 4,
  "JCB": 5,
  "LEUMI_CARD": 6
} as const

export const CardTypes = {
  "ISSUER": 0,
  "MASTERCARD": 1,
  "VISA": 2,
  "MAESTRO": 3
} as const

export const TranModes = {
    /** Standard */
    "STANDARD": "A",
    /** Verification (J5) */
    "VERIFICATION_J5": "V",
    /** Create token without checking card */
    "CREATE_TOKEN_NO_VERIFICATION": "K",
    /** Verification (J2) */
    "VERIFICATION_J2": "N",
    /** Standard with token */
    "STANDARD_WITH_TOKEN": "AK",
    /** Verification (J5) with token */
    "VERIFICATION_WITH_TOKEN": "VK",
    /** Verification (J5) with token */
    "CREATE_TOKEN_WITH_TOKEN": "NK"
} as const

export const Languages ={
  "Hebrew" : "il",
  "Arabic": "ar",
  "Russian": "ru",
  "Spanish": "es",
  "German": "de",
  "French": "fr",
  "Japanese": "jp"
} as const

export const ResponseLanguages = {
  "HEBREW": "hebrew",
  "ENGLISH": "english"
} as const

export const CurrencyCodesNumeric = {
  "NIS": 1,
  "USD": 2,
  "EUR": 978,
  "GBP": 826
} as const

export const CurrencyCodesAlpha = {
  "ILS": "ILS",
  "USD": "USD",
  "EUR": "EUR",
} as const

export const RecurTransactions = {
  "MONTHLY_CUSTOMER_CHOICE": 4,
  "QUARTERLY_CUSTOMER_CHOICE": 5,
  "YEARLY_CUSTOMER_CHOICE": 7,
  "MONTHLY_NOT_CUSTOMER_CHOICE": "4_approved",
  "QUARTERLY_NOT_CUSTOMER_CHOICE": "5_approved",
  "YEARLY_NOT_CUSTOMER_CHOICE": "7_approved"
} as const

export const StandingOrderStatuses = {
  "ACTIVE": "active",
  "INACTIVE": "inactive"
} as const

export const ChargeFrequencies = {
  "WEEKLY": "weekly",
  "MONTHLY": "monthly",
  "QUARTERLY": "quarterly",
  "HALF_YEARLY": "half-yearly",
  "YEARLY": "yearly"
} as const

export const DiscountTypes = {
  "FIXED": "fixed",
  "PERCENT": "percent"
} as const

export const BitUnitTypes  = {
  "UNIT": 1,
  "GRAM": 2,
  "KILOGRAM": 3,
  "TON": 4,
  "DAY": 5,
  "WEEK": 6,
  "MONTH": 7,
  "YEAR": 8,
  "CENTIMETER": 9,
  "METER": 10,
  "KILOMETER": 11,
  "MB": 12,
  "GB": 13,
  "TB": 14,
  "HOUR": 15,
  "LITRE": 16
} as const

export const PriceTypes = {
  "NET": "N",
  "GROSS": "G"
} as const

export const BitItemTypes = {
  "ITEM": "I",
  "SHIPPING": "S",
  "COUPON": "C"
} as const

export const ShvaResponseCodesEn = {
  "shva": "Pending SHVA response.",
  "000": "Transaction approved.",
  "777": "Operation completed (success code for transactions not recorded, including J2 and J5)",
  "001": "Blocked, confiscate card. Please check and re-enter the credit number.",
  "002": "Stolen, confiscate card. Please check and re-enter the credit number.",
  "003": "Contact credit company for transaction approval.",
  "004": "Refusal. Contact the card owner to verify the reason with their credit company.",
  "005": "Forged, confiscate card.",
  "006": "Incorrect identity number or CVV.",
  "007": "Invalid CAVV/UCAF.",
  "008": "Invalid AVS.",
  "009": "Communication unsuccessful.",
  "010": "Partial confirmation.",
  "011": "Transaction denied: lack of points/stars/miles/other benefits.",
  "012": "Unauthorized card for this terminal.",
  "013": "Incorrect balance code.",
  "014": "Card not assigned to network.",
  "015": "Expired card. Please check the expiration date again.",
  "016": "Unauthorized currency.",
  "017": "Unauthorized credit type for this transaction.",
  "026": "Incorrect ID number. Please check the ID number again.",
  "041": "Exit for inquiry required only for ceiling with transaction parameter J2.",
  "042": "Exit for inquiry required not only for ceiling, with transaction parameter J2.",
  "051": "Missing vector 1 file.",
  "052": "Missing vector 4 file.",
  "053": "Missing vector 6 file.",
  "055": "Missing vector 11 file.",
  "056": "Missing vector 12 file.",
  "057": "Missing vector 15 file.",
  "058": "Missing vector 18 file.",
  "059": "Missing vector 31 file.",
  "060": "Missing vector 34 file.",
  "061": "Missing vector 41 file.",
  "062": "Missing vector 44 file.",
  "063": "Missing vector 64 file.",
  "064": "Missing vector 80 file.",
  "065": "Missing vector 81 file.",
  "066": "Missing vector 82 file.",
  "067": "Missing vector 83 file.",
  "068": "Missing vector 90 file.",
  "069": "Missing vector 91 file.",
  "070": "Missing vector 92 file.",
  "071": "Missing vector 93 file.",
  "073": "Missing PARAM_3_1 file.",
  "074": "Missing PARAM_3_2 file.",
  "075": "Missing PARAM_3_3 file.",
  "076": "Missing PARAM_3_4 file.",
  "077": "Missing PARAM_361 file.",
  "078": "Missing PARAM_363 file.",
  "079": "Missing PARAM_364 file.",
  "080": "Missing PARAM_61 file.",
  "081": "Missing PARAM_62 file.",
  "082": "Missing PARAM_63 file.",
  "083": "Missing CEIL_41 file.",
  "084": "Missing CEIL_42 file.",
  "085": "Missing CEIL_43 file.",
  "086": "Missing CEIL_44 file.",
  "087": "Missing DATA file.",
  "088": "Missing JENR file.",
  "089": "Missing Start file.",
  "101": "Missing entry in vector 1.",
  "103": "Missing entry in vector 4.",
  "104": "Missing entry in vector 6.",
  "106": "Missing entry in vector 11.",
  "107": "Missing entry in vector 12.",
  "108": "Missing entry in vector 15.",
  "110": "Missing entry in vector 18.",
  "111": "Missing entry in vector 31.",
  "112": "Missing entry in vector 34.",
  "113": "Missing entry in vector 41.",
  "114": "Missing entry in vector 44.",
  "116": "Missing entry in vector 64.",
  "117": "Missing entry in vector 81.",
  "118": "Missing entry in vector 82.",
  "119": "Missing entry in vector 83.",
  "120": "Missing entry in vector 90.",
  "121": "Missing entry in vector 91.",
  "122": "Missing entry in vector 92.",
  "123": "Missing entry in vector 93.",
  "141": "Terminal not authorized to clear transaction brand.",
  "142": "Missing appropriate entry in parameters file 3.3.",
  "143": "Missing entry in club domains file 3.6.1.",
  "144": "Missing entry in club domains file 3.6.3.",
  "145": "Missing entry in club domains file 3.6.4.",
  "146": "Missing entry in ceilings file for PL cards 4.1.",
  "147": "Missing entry in ceilings file for non-PL Israeli cards method 0 4.2.",
  "148": "Missing entry in ceilings file for non-PL Israeli cards method 1 4.3.",
  "149": "Missing entry in ceilings file for tourist cards 4.4.",
  "150": "Missing entry in valid cards file - Isracard.",
  "151": "Missing entry in valid cards file - Cal.",
  "152": "Missing entry in valid cards file - future issuer.",
  "182": "Vector 4 values error.",
  "183": "Vector 6/12 values error.",
  "186": "Vector 18 values error.",
  "187": "Vector 34 values error.",
  "188": "Vector 64 values error.",
  "190": "Vector 90 values error.",
  "191": "Invalid data in issuer permissions vector.",
  "192": "Invalid data in parameter set.",
  "193": "Invalid data in terminal level parameters file.",
  "300": "No authorization for transaction type - acquirer authorization.",
  "301": "No authorization for currency - acquirer authorization - no acquirer approval for ISO currency. The terminal is not authorized by the credit card company for foreign currency transactions.",
  "303": "No acquirer authorization to perform a transaction when the card is not present - the terminal is not approved for a telephone transaction.",
  "304": "No authorization for credit - acquirer authorization - card not authorized to perform at this terminal or no approval for such a transaction.",
  "308": "No authorization for installment - acquirer authorization.",
  "309": "No acquirer authorization for credit at a fixed date.",
  "310": "No authorization to pre-enter an approval number.",
  "311": "No authorization to conduct transactions for service code 587 - the terminal is not approved for a card with service code 085.",
  "312": "No acquirer authorization for deferred credit.",
  "313": "No acquirer authorization for benefits.",
  "314": "No acquirer authorization for promotions.",
  "315": "No acquirer authorization for a specific promotion code.",
  "316": "No acquirer authorization for a loading transaction.",
  "317": "No acquirer authorization for loading/unloading in combination with a currency code.",
  "318": "No acquirer authorization for currency in this type of credit - no acquirer approval for ISO currency.",
  "319": "No acquirer authorization for tip.",
  "341": "No authorization for transaction - issuer authorization.",
  "342": "No authorization for currency - issuer authorization - no approval for the brand for ISO currency.",
  "343": "No issuer authorization to perform a transaction when the card is not present.",
  "344": "No authorization for credit - issuer authorization - card not authorized to perform a transaction with this type of credit.",
  "348": "No authorization to perform a merchant-initiated authorization request.",
  "349": "No appropriate authorization to perform a request for authorization without a transaction J5.",
  "350": "No issuer authorization for benefits.",
  "351": "No issuer authorization for deferred credit.",
  "352": "No issuer authorization for a loading transaction.",
  "353": "No issuer authorization for loading/unloading with a payment method code.",
  "354": "No issuer authorization for currency in this type of credit - no approval for the brand for ISO currency.",
  "381": "No authorization to perform a contactless transaction above the maximum amount.",
  "382": "In a terminal defined as self-service, only self-service transactions can be performed.",
  "384": "Terminal defined as multi-vendor/beneficiary - missing vendor/beneficiary number.",
  "385": "In a terminal defined as an e-commerce terminal, it is mandatory to pass eci.",
  "401": "Number of installments greater than the maximum value of the installments number field.",
  "402": "Number of installments less than the minimum value of the installments number field.",
  "403": "Transaction amount less than the minimum amount for payment field value.",
  "404": "Installments number field not entered.",
  "405": "Missing data for first/fixed payment amount.",
  "406": "Total transaction amount different from first payment amount + fixed payment amount * number of installments - error in payments - transaction amount should be equal to first payment amount and fixed payment amount.",
  "407": "First payment amount greater than transaction amount.",
  "408": "Fixed payment amount greater than transaction amount.",
  "409": "First payment amount and fixed payment amounts greater than transaction amount.",
  "410": "First payment amount and fixed payment amounts less than transaction amount.",
  "411": "Number of installments greater than allowed for this card.",
  "412": "Number of installments less than allowed for this card.",
  "413": "First payment amount less than allowed for this card.",
  "414": "Fixed payment amount less than allowed for this card.",
  "415": "First payment amount greater than allowed for this card.",
  "416": "Fixed payment amount greater than allowed for this card.",
  "417": "First payment amount and fixed payment amounts greater than allowed for this card.",
  "418": "First payment amount and fixed payment amounts less than allowed for this card.",
  "419": "First payment amount and fixed payment amounts not equal to transaction amount.",
  "420": "First payment amount and fixed payment amounts not matching the allowed amount for this card.",
  "421": "General error - invalid data.",
  "422": "Error in building ISO message.",
  "424": "Non-numeric field.",
  "425": "Duplicate record.",
  "426": "Amount increased after credit checks.",
  "428": "Missing service code on card.",
  "429": "Card not valid according to valid cards file.",
  "431": "General failure.",
  "432": "No permission to pass card through magnetic reader.",
  "433": "Required to pass through PinPad.",
  "434": "Forbidden to pass card in PinPad device.",
  "435": "Device not set to pass magnetic CTL card.",
  "436": "Device not set to pass EMV CTL card.",
  "439": "No authorization for credit type according to transaction type.",
  "440": "Tourist card not authorized for this type of credit.",
  "441": "No authorization to perform transaction type - card exists in vector 80.",
  "442": "Do not perform Stand-in for authorization verification for this acquirer.",
  "443": "Cannot perform cancellation transaction - card not found in existing transactions file in terminal.",
  "445": "In an immediate debit card, only an immediate debit credit can be performed.",
  "447": "Incorrect credit card number.",
  "448": "Address (City, Street, House number & Zip code) is necessary.",
  "449": "Zip code is necessary.",
  "450": "Promotion code out of range, should be within 1-12.",
  "451": "Error during transaction record building.",
  "452": "In a loading/unloading/balance inquiry transaction, payment method code field must be entered.",
  "453": "No possibility to cancel a unloading transaction 7.9.3.",
  "455": "Cannot perform forced debit transaction when an approval request is required (except for ceilings).",
  "456": "Card found in transactions file with response code 'confiscate card'.",
  "457": "In an immediate debit card, a normal debit/credit/cancellation transaction is allowed.",
  "458": "Club code out of range.",
  "470": "In a standing order transaction, the payments amount is higher than the transaction amount field.",
  "471": "In a standing order transaction, the installment number is greater than the total number of installments.",
  "472": "In a debit transaction with cash, cash amount must be entered.",
  "473": "In a debit transaction with cash, the cash amount must be less than the transaction amount.",
  "474": "Initialization transaction in standing order requires parameter J5.",
  "475": "Standing order transaction requires one of the fields: number of installments or total amount.",
  "476": "Installment transaction in standing order requires installment number field.",
  "477": "Installment transaction in standing order requires identifier number of initialization transaction.",
  "478": "Installment transaction in standing order requires approval number of initialization transaction.",
  "479": "Installment transaction in standing order requires date and time fields of initialization transaction.",
  "480": "Missing field approving source transaction.",
  "481": "Missing number of units field when the transaction is performed with a payment method code different from currency.",
  "482": "In a reloadable card, a normal debit/credit/cancellation/loading/balance inquiry transaction is allowed.",
  "483": "Transaction with a fuel card at a fuel terminal must enter vehicle number.",
  "484": "Typed vehicle number different from the vehicle number burned on the magnetic stripe/bank number different from 012/left digits of branch number different from 44.",
  "485": "Vehicle number shorter than 6 digits/different from the vehicle number appearing on channel 2 (position 34 on channel 2) Leumi Card fuel characteristic card.",
  "486": "Obligation to enter meter reading (position 30 on channel 2) Leumi Card fuel characteristic card.",
  "487": "Only in a terminal defined as two-stage fuel can the obligation update be used.",
  "489": "In a fuel card, only a normal debit transaction is allowed (cancellation transaction forbidden).",
  "490": "In fuel/fuel card/fuel club cards, transactions can only be performed at fuel terminals.",
  "491": "Transaction involving conversion must contain all fields conversion_amount_06, conversion_rate_09, conversion_currency_51.",
  "492": "No conversion on transactions in shekel/dollar.",
  "493": "In a transaction involving a benefit, only one of the following fields must be present: discount amount/number of units/% discount.",
  "494": "Different terminal number.",
  "495": "No fallback authorization.",
  "496": "Cannot attach credit different from credit/installments.",
  "497": "Cannot attach to dollar/index in a currency different from shekel.",
  "498": "Local Isracard card separator must be in position 18.",
  "500": "Transaction stopped by user.",
  "504": "Mismatch between card data source field and card number field.",
  "505": "Illegal value in transaction type field.",
  "506": "Illegal value in eci field.",
  "507": "Actual transaction amount higher than the approved amount.",
  "509": "Error during writing to transactions file.",
  "512": "Cannot enter approval received from voice response for this transaction.",
  "551": "Response message does not match request message.",
  "552": "Error in field 55.",
  "553": "Error received from the tandem.",
  "554": "Field mcc_18 missing in response message.",
  "555": "Field response_code_25 missing in response message.",
  "556": "Field rrn_37 missing in response message.",
  "557": "Field comp_retailer_num_42 missing in response message.",
  "558": "Field auth_code_43 missing in response message.",
  "559": "Field f39_response_39 missing in response response.",
  "560": "Field authorization_no_38 missing in response message.",
  "561": "Field additional_data_48.solek_auth_no missing/empty in response message.",
  "562": "One of the fields conversion_amount_06, conversion_rate_09, conversion_currency_51 missing in response message.",
  "563": "Field value does not match the received approval numbers auth_code_43.",
  "564": "Field additional_amounts54.cashback_amount missing/empty in response message.",
  "565": "Mismatch between fields 25 and 43.",
  "566": "In a terminal defined as supporting two-stage fuel, it is mandatory to return fields 90,119.",
  "567": "Fields 25,127 invalid in obligation update message in a terminal defined as two-stage fuel.",
  "700": "Transaction declined by PinPad device.",
  "701": "Error in PinPad device.",
  "702": "Invalid COM exit.",
  "703": "Transaction failed.",
  "704": "Transaction cancelled.",
  "705": "Transaction stopped by user.",
  "706": "Waiting time too long.",
  "707": "User removed card before transaction completion.",
  "708": "PINPAD_UserRetriesExceeded.",
  "709": "PINPAD_PINPadTimeout.",
  "710": "Communication fault with device.",
  "711": "PINPAD_PINPadMessageError.",
  "712": "PINPAD_PINPadNotInitialized.",
  "713": "PINPAD_PINPadCardReadError.",
  "714": "PINPAD_ReaderTimeout.",
  "715": "PINPAD_ReaderCommsError.",
  "716": "PINPAD_ReaderMessageError.",
  "717": "PINPAD_HostMessageError.",
  "718": "PINPAD_HostConfigError.",
  "719": "PINPAD_HostKeyError.",
  "720": "PINPAD_HostConnectError.",
  "721": "PINPAD_HostTransmitError.",
  "722": "PINPAD_HostReceiveError.",
  "723": "PINPAD_HostTimeout.",
  "724": "PINVerificationNotSupportedByCard.",
  "725": "PINVerificationFailed.",
  "726": "Error in receiving config.xml file.",
  "730": "Device approved transaction."
} as const
export const shvaResponseCodes = {
  "000": "מאושר",
  "777": "פעולה הושלמה (קוד הצלחה לפעולות בהן לא נרשמת עסקה, כוללJ2  ו- J5)",
  "001": "כרטיס חסום",
  "002": "גנוב החרם כרטיס",
  "003": "התקשר לחברת האשראי",
  "004": "העסקה לא אושרה ",
  "005": "כרטיס מזוייף החרם",
  "006": "דחה עסקה : cvc2/id שגוי",
  "007": "דחה עסקה : cavv/ucaf שגוי ",
  "009": "דחייה - נתק בתקשורת",
  "010": "אישור חלקי ",
  "011": "דחה עסקה : חוסר בנקודות/כוכבים/מיילים/הטבה אחרת",
  "012": "הכרטיס לא מורשה במסוף",
  "013": "דחה בקשה. קוד יתרה שגוי",
  "014": "דחייה. כרטיס לא משוייך לרשת",
  "015": "דחה עסקה : הכרטיס אינו בתוקף",
  "016": "דחייה - אין הרשאה לסוג מטבע ",
  "017": "דחייה - אין הרשאה לסוג אשראי בעסקה",
  "026": "דחה עסקה - id שגוי",
  "041": "ישנה חובת יציאה לשאילתא בגין תקרה בלבד לעסקה עם פרמטר J2",
  "042": "ישנה חובת יציאה לשאילתא לא רק בגין תקרה, לעסקה עם פרמטר J2 ",
  "051": "חסר קובץ ווקטור 1",
  "052": "חסר קובץ ווקטור 4",
  "053": "חסר קובץ ווקטור 6",
  "055": "חסר קובץ ווקטור 11",
  "056": "חסר קובץ ווקטור 12",
  "057": "חסר קובץ ווקטור 15",
  "058": "חסר קובץ ווקטור 18",
  "059": "חסר קובץ ווקטור 31",
  "060": "חסר קובץ ווקטור 34",
  "061": "חסר קובץ ווקטור 41",
  "062": "חסר קובץ ווקטור 44",
  "063": "חסר קובץ ווקטור 64",
  "064": "חסר קובץ ווקטור 80",
  "065": "חסר קובץ ווקטור 81",
  "066": "חסר קובץ ווקטור 82",
  "067": "חסר קובץ ווקטור 83",
  "068": "חסר קובץ ווקטור 90",
  "069": "חסר קובץ ווקטור 91",
  "070": "חסר קובץ ווקטור 92",
  "071": "חסר קובץ ווקטור 93",
  "073": "חסר קובץ  PARAM_3_1",
  "074": "חסר קובץ  PARAM_3_2",
  "075": "חסר קובץ  PARAM_3_3 ",
  "076": "חסר קובץ  PARAM_3_4",
  "077": "חסר קובץ  PARAM_361",
  "078": "חסר קובץ  PARAM_363",
  "079": "חסר קובץ  PARAM_364",
  "080": "חסר קובץ  PARAM_61",
  "081": "חסר קובץ  PARAM_62",
  "082": "חסר קובץ   PARAM_63",
  "083": "חסר קובץ  CEIL_41",
  "084": "חסר קובץ  CEIL_42",
  "085": "חסר קובץ  CEIL_43",
  "086": "חסר קובץ  CEIL_44",
  "087": "חסר קובץ DATA",
  "088": "חסר קובץ JENR",
  "089": "חבר קובץ Start",
  "101": "חסרה כניסה בוקטור 1",
  "103": "חסרה כניסה בוקטור 4",
  "104": "חסרה כניסה בוקטור 6",
  "106": "חסרה כניסה בוקטור 11 ",
  "107": "חסרה כניסה בוקטור 12",
  "108": "חסרה כניסה בוקטור 15",
  "110": "חסרה כניסה בוקטור 18",
  "111": "חסרה כניסה בוקטור 31",
  "112": "חסרה כניסה בוקטור 34",
  "113": "חסרה כניסה בוקטור 41",
  "114": "חסרה כניסה בוקטור 44",
  "116": "חסרה כניסה בוקטור 64",
  "117": "חסרה כניסה בוקטור 81",
  "118": "חסרה כניסה בוקטור 82",
  "119": "חסרה כניסה בוקטור 83",
  "120": "חסרה כניסה בוקטור 90",
  "121": "חסרה כניסה בוקטור 91",
  "122": "חסרה כניסה בוקטור 92",
  "123": "חסרה כניסה בוקטור 93",
  "141": "חסרה כניסה מתאימה בקובץ פרמטרים 3.2",
  "142": "חסרה כניסה מתאימה בקובץ פרמטרים 3.3",
  "143": "חסרה כניסה בקובץ תחומי מועדון 3.6.1 ",
  "144": "חסרה כניסה בקובץ תחומי מועדון 3.6.3 ",
  "145": "חסרה כניסה בקובץ תחומי מועדון 3.6.4 ",
  "146": "חסרה כניסה בקובץ תקרות לכרטיסי PL  4.1",
  "147": "חסרה כניסה בקובץ תקרות לכרטיסים ישראלים שאינם PL שיטה 0 4.2",
  "148": "חסרה כניסה בקובץ תקרות לכרטיסים ישראלים שאינם PL שיטה 1 4.3",
  "149": "חסרה כניסה בקובץ תקרות לכרטיסי תייר 4.4",
  "150": "חסרה כניסה בקובץ כרטיסים תקפים - ישראכרט",
  "151": "חסרה כניסה בקובץ כרטיסים תקפים - כאל",
  "152": "חסרה כניסה בקובץ כרטיסים תקפים - מנפיק עתידי",
  "182": "שגיאה בערכי וקטור 4",
  "183": "״שגיאה בערכי וקטור 6/12",
  "186": "שגיאה בערכי וקטור 18",
  "187": "שגיאה בערכי וקטור 34",
  "188": "שגיאה בערכי וקטור 64",
  "190": "שגיאה בערכי וקטור 90",
  "191": "נתונים לא תקינים בוקטור הרשאות מנפיק",
  "192": "נתונים לא ולידים בסט הפרמטרים",
  "193": "נתונים לא ולידים בקובץ פרמטרים ברמת מסוף",
  "300": "אין הרשאה לסוג עסקה - הרשאת סולק - ",
  "301": "אין הרשאה למטבע - הרשאת סולק ",
  "303": "אין הרשאת סולק לביצוע עסקה כאשר הכרטיס לא נוכח",
  "304": "אין הרשאה לאשראי - הרשאת סולק",
  "308": "אין הרשאה להצמדה - הרשאת סולק",
  "309": "אין הרשאת סולק לאשראי במועד קבוע",
  "310": "אין הרשאה להקלדת מספר אישור מראש",
  "311": "אין הרשאה לבצע עסקאות לקוד שרות 587",
  "312": "אין הרשאת סולק לאשראי דחוי",
  "313": "אין הרשאת סולק להטבות",
  "314": "אין הרשאת סולק למבצעים",
  "315": "אין הרשאת סולק לקוד מבצע ספציפי",
  "316": "אין הרשאת סולק לעסקת טעינה",
  "317": "אין הרשאת סולק לטעינה/פריקה בקוד אמצעי התשלום בשילוב קוד מטבע",
  "318": "אין הרשאת סולק למטבע בסוג אשראי זה",
  "319": "אין הרשאת סולק לטיפ",
  "341": "אין הרשאה לעסקה - הרשאת מנפיק",
  "342": "אין הרשאה למטבע - הרשאת מנפיק",
  "343": "אין הרשאת מנפיק לביצוע עסקה כאשר הכרטיס לא נוכח ",
  "344": "אין הרשאה לאשראי - הרשאת מנפיק",
  "348": "אין הרשאה לביצוע אישור בקשה יזומה ע״י  קמעונאי",
  "349": "אין הרשאה מתאימה לביצוע בקשה לאישור ללא עסקה J5",
  "350": "אין הרשאת מנפיק להטבות",
  "351": "אין הרשאת מנפיק לאשראי דחוי",
  "352": "אין הרשאת מנפיק לעסקת טעינה",
  "353": "אין הרשאת מנפיק לטעינה/פריקה בקוד אמצעי התשלום",
  "354": "אין הרשאת מנפיק למטבע בסוג אשראי זה",
  "381": "אין הרשאה לבצע עסקת contactless  מעל סכום מרבי",
  "382": "במסוף המוגדר כשרות עצמי ניתן לבצע רק עסקאות בשירות עצמי",
  "384": "מסוף מוגדר כרב-ספק /מוטב - חסר מספר ספק/מוטב",
  "385": "במסוף המוגדר כמסוף סחר אלקטרוני חובה להעביר eci ",
  "401": "מספר התשלומים גדול מערך שדה מספר תשלומים מקסימלי",
  "402": "מספר התשלומים קטן מערך שדה מספר תשלומים מינימלי",
  "403": "סכום העסקה קטן מערך שדה סכום מינמלי לתשלום !!!",
  "404": "לא הוזן שדה מספר תשלומים",
  "405": "חסר נתון סכום תשלום ראשון /קבוע",
  "406": "סה״כ סכום העסקה שונה מסכום תשלום ראשון + סכום תשלום קבוע * מספר תשלומים",
  "408": "ערוץ 2  קצר  מ 37-תווים",
  "410": "דחיה מסיבת  dcode ",
  "414": "בעסקה עם חיוב בתאריך קבוע הוכנס תאריך מאוחר משנה מבצוע העיסקה",
  "415": "הוזנו נתונים לא תקינים",
  "416": "תאריך תוקף לא במבנה תקין",
  "417": "מספר מסוף אינו תקין",
  "418": "חסרים פרמטרים חיוניים ",
  "419": "שגיאה בהעברת מאפיין clientInputPan",
  "420": "מספר כרטיס לא ולידי -במצב של הזנת ערוץ 2 בעסקה ללא כרטיס נוכח",
  "421": "שגיאה כללי- נתונים לא ולידים",
  "422": "שגיאה בבנית מסר  ISO",
  "424": "שדה לא נומרי",
  "425": "רשומה כפולה",
  "426": "הסכום הוגדל לאחר ביצוע בדיקות אשראית",
  "428": "חסר קוד שרות בכרטיס",
  "429": "כרטיס אינו תקף לפי קובץ כרטיסים תקפים",
  "431": "שגיאה כללית",
  "432": "אין הראשה להעברת כרטיס דרך קורא מגנטי",
  "433": "חיוב להעביר ב - PinPad",
  "434": "אסור  להעביר כרטיס במכשיר ה- PinPad",
  "435": "המכשיר לא מוגדר להעברת כרטיס מגנטי CTL",
  "436": "המכשיר לא מוגדר להעברת כרטיס EMV CTL",
  "439": "אין הרשאה לסוג אשראי לפי סוג עסקה",
  "440": "כרטיס תייר אינו מורשה לסוג אשראי זה",
  "441": "אין הרשאה לביצוע סוג עסקה - כרטיס קיים בוקטור 80",
  "442": "אין לבצע Stand-in לאימות אישור לסולק זה",
  "443": "לא ניתן לבצע עסקת ביטול  - כרטיס לא נמצא בקובץ תנועות הקיים במסוף",
  "445": "בכרטיס חיוב מיידי ניתן לבצע אשראי חיוב מיידי בלבד",
  "447": "מספר כרטיס שגוי",
  "448": "חיוב להקליד כתובת לקוח (מיקוד ,מספר בית ועיר)",
  "449": "חיוב להקליד מיקוד",
  "450": "קוד מבצע מחוץ לתחום, צ״ל בתחום 1-12",
  "451": "שגיאה במהלך בנית רשומת עסקה",
  "452": "בעסקת טעינה/פריקה/בירור יתרה חיוב להזין שדה קוד אמצעי תשלום",
  "453": "אין אפשרות לבטל עסקת פריקה 7.9.3",
  "455": "לא ניתן לבצע עסקת חיוב מאולצת כאשר נדרשת בקשה לאישור (למעט תקרות)",
  "456": "כרטיס נמצא בקובץ תנועות עם קוד תשובה 'החרם כרטיס'",
  "457": "בכרטיס חיוב מיידי מותרת עסקת חיוב רגילה/זיכוי/ביטול",
  "458": "קוד מועדון לא בתחום",
  "470": "בעסקת הו״ק סכום התשלומים גבוה משדה סכום העסקה",
  "471": "בעסקת הו״ק מספר תשלום תורן גדול מסה״כ מספר התשלומים",
  "472": "בעסקת חיוב עם מזומן חיוב להזין סכום במזומן",
  "473": "בעסקת חיוב עם מזומן סכום המזומן צריך להיות קטן מסכום העסקה",
  "474": "עסקת איתחול בהוראת קבע מחייבת פרמטר J5",
  "475": "עסקת ה״ק מחייבת אחד מהשדות :מספר תשלומים או סכום כולל",
  "476": "עסקת תורן בהוראת קבע מחייבת שדה מספר תשלום",
  "477": "עסקת תורן בהוראת קבע מחייבת מספר מזהה של עסקת איתחול",
  "478": "עסקת תורן בהוראת קבע מחייבת מספר אישור של עסקת איתחול",
  "479": "עסקת תורן בהוראת קבע מחייבת שדות תאריך וזמן עסקת איתחול",
  "480": "חסר שדה מאשר עסקת מקור ",
  "481": "חסר שדה מספר יחידות כאשר העסקה מתבצעת בקוד אמצעי תשלום השונה ממטבע",
  "482": "בכרטיס נטען מותרת עסקת חיוב רגילה/זיכוי/ביטול/פריקה/טעינה/בירור יתרה",
  "483": "עסקה עם כרטיס דלק במסוף דלק חיוב להזין מספר רכב",
  "484": "מספר רכב המוקלד שונה ממספר הרכב הצרוב ע״ג הפס המגנטי/מספר בנק שונה מ-012/ספרות שמאליות של מספר הסניף שונה מ- 44",
  "485": "מספר רכב קצר  מ- 6 ספרות /שונה ממספר הרכב המופיע ע״ג ערוץ 2 (פוזיציה 34 בערוץ 2) כרטיס מאפיין דלק של לאומי קארד",
  "486": "ישנה חובת הקלדת קריאת מונה (פוזיציה 30 בערוץ 2)  כרטיס מאפיין דלק של לאומי קארד",
  "487": "רק במסוף המוגדר כדלק דו שלבי ניתן להשתמש בעדכון אובליגו",
  "489": "בכרטיס דלקן מותרת עסקת חיוב רגילה בלבד (עסקת ביטול אסורה)",
  "490": "בכרטיסי דלק/דלקן/דלק מועדון ניתן לבצע עסקאות רק במסופי דלק",
  "491": "עסקה הכוללת המרה חייבת להכיל את כל השדות conversion_amount_06, conversion_rate_09, conversion_currency_51",
  "492": "אין המרה על עסקאות שקל /דולר",
  "493": "בעסקה הכוללת הטבה חיוב שיהיו רק אחד מהשדות הבאים: סכום הנחה/מספר יחידות/ % ההנחה",
  "494": "מספר מסוף שונה",
  "495": "אין הרשאת  fallback",
  "496": "לא ניתן להצמיד אשראי השונה מאשראי קרדיט/תשלומים",
  "497": "לא ניתן להצמיד לדולר/מדד במטבע השונה משקל",
  "498": "כרטיס ישראכרט מקומי הספרטור  צ״ל בפוזיציה 18",
  "500": "העסקה הופסקה ע״י המשתמש",
  "504": "חוסר התאמה בין שדה מקור נתוני הכרטיס לשדה מספר כרטיס",
  "505": "ערך לא חוקי בשדה סוג עסקה",
  "506": "ערך לא חוקי בשדה eci",
  "507": "סכום העסקה בפועל גבוה מהסכום המאושר",
  "509": "שגיאה במהלך כתיבה לקובץ תנועות",
  "512": "לא ניתן להכניס אישור שהתקבל ממענה קולי לעסקה זו",
  "551": "מסר תשובה אינו מתאים למסר הבקשה",
  "552": "שגיאה בשדה 55",
  "553": "התקבלה שגיאה מהטנדם",
  "554": "במסר התשובה חסר שדה  mcc_18",
  "555": "במסר התשובה חסר שדה  response_code_25",
  "556": "במסר התשובה חסר שדה rrn_37 ",
  "557": "במסר התשובה חסר שדה  comp_retailer_num_42",
  "558": "במסר התשובה חסר שדה  auth_code_43",
  "559": "במסר התשובה חסר שדה f39_response_39",
  "560": "במסר התשובה חסר שדה authorization_no_38",
  "561": "במסר התשובה חסר / ריק שדה  additional_data_48.solek_auth_no",
  "562": "במסר התשובה חסר אחד מהשדות conversion_amount_06, conversion_rate_09, conversion_currency_51     ",
  "563": "ערך השדה אינו מתאים למספרי האישור שהתקבלו auth_code_43",
  "564": "במסר התשובה חסר/ריק שדה additional_amounts54.cashback_amount",
  "565": "אי-התאמה בין שדה 25 לשדה 43",
  "566": "במסוף המוגדר כתומך בדלק דו-שלבי יש חובה להחזיר שדות 90,119",
  "567": "שדות 25,127 לא תקינים במסר עידכון אובליגו במסוף המוגדר כדלק דו-שלבי",
  "997": "שגיאה כללית",
  "998": "ERROR_IN_NEG_FILE",
  "700": "עסקה נדחתה ע״י מכשיר  PinPad",
  "701": "שגיאה במכשיר  pinpad",
  "702": "יציאת com  לא תקינה",
  "703": "עסקה נכשלה",
  "704": "עסקה בוטלה",
  "705": "עסקה הופסקה ע״י המשתמש",
  "706": "זמן המתנה ארוך מדי",
  "707": "משתמש הוציא כרטיס לפני סיום ביצוע העסקה",
  "708": "PINPAD_UserRetriesExceeded",
  "709": "PINPAD_PINPadTimeout",
  "710": "תקלת תקשורת עם מכשיר",
  "711": "PINPAD_PINPadMessageError",
  "712": "PINPAD_PINPadNotInitialized",
  "713": "PINPAD_PINPadCardReadError",
  "714": "PINPAD_ReaderTimeout",
  "715": "PINPAD_ReaderCommsError",
  "716": "PINPAD_ReaderMessageError",
  "717": "PINPAD_HostMessageError",
  "718": "PINPAD_HostConfigError",
  "719": "PINPAD_HostKeyError",
  "720": "PINPAD_HostConnectError",
  "721": "PINPAD_HostTransmitError",
  "722": "PINPAD_HostReceiveError",
  "723": "PINPAD_HostTimeout",
  "724": "PINVerificationNotSupportedByCard",
  "725": "PINVerificationFailed",
  "726": "שגיאה בקליטת קובץ config.xml",
  "730": "מכשיר אישר עסקה בניגוד להחלטת אשראית",
  "731": "כרטיס לא הוכנס"

} as const